jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    NODE_VERSION: 10.15.0
    SPRING_OUTPUT_ANSI_ENABLED: NEVER
    SPRING_JPA_SHOW_SQL: false
    JHI_DISABLE_WEBPACK_LOGS: true

  steps:
  #----------------------------------------------------------------------
  # Install all tools and check configuration
  #----------------------------------------------------------------------
  - task: NodeTool@0
    inputs:
      versionSpec: '10.15.0'
    displayName: 'TOOLS: install Node.js'
  - script: sudo npm install -g npm
    displayName: 'TOOLS: update NPM'
  - script: sudo chown -R vsts:docker /home/vsts/.npm/
    displayName: 'BUGS-FIX: change /home/vsts/.npm/ permission'
  - script: sudo /etc/init.d/mysql stop
    displayName: 'TOOLS: stop MySQL'
  #----------------------------------------------------------------------
  # Tests
  #----------------------------------------------------------------------
  - script: npm install
    displayName: 'INSTALL: launch npm install'
  - script: |
      chmod +x mvnw
      ./mvnw clean test
    displayName: 'TESTS: backend'
  - script: ./mvnw verify -Pprod -DskipTests
    displayName: 'TESTS: packaging'
